services:
  redis:
    image: "redis:6.2-alpine"
    container_name: "redis-container"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
